from typing import Protocol

from src.domain.accounts.schemas.user import UsersSchemaAuth, UsersSchemaAdd, TokenJWT
from src.domain.appointments.schemas.appointment import AppointmentsSchemaBase, AppointmentsSchema


class AppointmentsServiceProtocol(Protocol):
    async def get_by_username(self, username: str) -> AppointmentsSchemaBase | None: ...

    async def create_appointment(self, appointment: AppointmentsSchema) -> AppointmentsSchemaBase: ...

    async def get_by_email_appointment(self, email: str) -> AppointmentsSchemaBase | None: ...

    async def get_all_appointment(self) -> AppointmentsSchemaBase | None: ...

    async def delete_appointment(self, appointment: int) -> AppointmentsSchemaBase: ...


class AppointmentsRepositoryProtocol(Protocol):
    async def get_by_username(self, username: str) -> AppointmentsSchemaBase | None: ...

    async def create(self, appointment: AppointmentsSchema) -> AppointmentsSchemaBase: ...

    async def get_by_email(self, email: str) -> AppointmentsSchemaBase | None: ...

    async def get_all(self) -> AppointmentsSchemaBase | None: ...

    async def delete(self, appointment: int) -> AppointmentsSchemaBase: ...
