services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_book_and_go
    ports:
      - "3000:3000"
    networks:
      - app_book_and_go_network




  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: backend_book_and_go
    env_file:
      - .env.docker-compose
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB__NAME}
      DB_USER: ${DB__USER}
      DB_PASSWORD: ${DB__PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_book_and_go_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_book_and_go
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_book_and_go_network


  postgres:
    image: postgres:17
    container_name: postgres_book_and_go
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - "${DB__PORT}:5432"
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_book_and_go_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin__book_and_go
    env_file:
      - .env.docker-compose
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - app_book_and_go_network



networks:
  app_book_and_go_network:
    name: app_book_and_go_network
