"""Fix service uniqe

Revision ID: 853c7a247bff
Revises: bad7c6d9cfbf
Create Date: 2025-06-15 18:13:24.763363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853c7a247bff'
down_revision: Union[str, None] = 'bad7c6d9cfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_service_key'), 'appointments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('appointments_service_key'), 'appointments', ['service'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
