"""Add Appointment table to env alembic

Revision ID: bad7c6d9cfbf
Revises: b8784b3d981f
Create Date: 2025-06-15 17:49:57.286196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad7c6d9cfbf'
down_revision: Union[str, None] = 'b8784b3d981f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('service')
    )
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index(op.f('ix_appointments_name'), 'appointments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_name'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
