"""Fix model email and service unique

Revision ID: e3edebedf68f
Revises: 853c7a247bff
Create Date: 2025-06-15 19:32:35.386145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3edebedf68f'
down_revision: Union[str, None] = '853c7a247bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_email_key'), 'appointments', type_='unique')
    op.drop_constraint(op.f('appointments_phone_key'), 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_unique_constraint(op.f('appointments_phone_key'), 'appointments', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('appointments_email_key'), 'appointments', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
